use crate::stream_url::models::{HlsParams, StaticRendition};

const BASE: &str = "https://stream.mux.com";

/// Fetch an HLS (HTTP Live Streaming) playlist for the specified video asset,
/// with optional query parameters to
/// [modify playback behavior](https://docs.mux.com/guides/modify-playback-behavior).
///
/// URL pattern: `https://stream.mux.com/{PLAYBACK_ID}.m3u8`
pub fn hls_url(playback_id: &str, params: Option<HlsParams>) -> String {
    let base = format!("{}/{}.m3u8", BASE, playback_id);

    let Some(p) = params else {
        return base;
    };

    let mut qs: Vec<String> = Vec::new();
    if let Some(v) = p.asset_start_time {
        qs.push(format!("asset_start_time={}", v))
    }
    if let Some(v) = p.asset_end_time {
        qs.push(format!("asset_end_time={}", v))
    }
    if let Some(v) = p.program_start_time {
        qs.push(format!("program_start_time={}", v))
    }
    if let Some(v) = p.program_end_time {
        qs.push(format!("program_end_time={}", v))
    }
    if let Some(v) = p.default_subtitles_lang {
        qs.push(format!("default_subtitles_lang={}", v))
    }
    if let Some(v) = p.exclude_pdt {
        qs.push(format!("exclude_pdt={}", v))
    }
    if let Some(v) = p.max_resolution {
        qs.push(format!("max_resolution={}", v))
    }
    if let Some(v) = p.min_resolution {
        qs.push(format!("min_resolution={}", v))
    }
    if let Some(v) = p.redundant_streams {
        qs.push(format!("redundant_streams={}", v))
    }
    if let Some(v) = p.rendition_order {
        qs.push(format!("rendition_order={}", v))
    }
    if let Some(v) = p.roku_trick_play {
        qs.push(format!("roku_trick_play={}", v))
    }
    if let Some(v) = p.token {
        qs.push(format!("TOKEN={}", v))
    }

    append_query(base, qs)
}

/// Fetch an HLS manifest URL.
pub fn hls_manifest_url(playback_id: &str, params: Option<HlsParams>) -> String {
    hls_url(playback_id, params)
}

/// Fetch a static rendition (MP4 or M4A file) of the specified video asset.
/// [MP4 Support](https://docs.mux.com/guides/enable-static-mp4-renditions) must
/// be enabled on the asset before using these URLs.
///
/// URL pattern: `https://stream.mux.com/{PLAYBACK_ID}/{filename}`
pub fn static_rendition_url(
    playback_id: &str,
    rendition: StaticRendition,
    token: Option<&str>,
) -> String {
    let base = format!("{}/{}/{}", BASE, playback_id, rendition.filename());
    match token {
        Some(t) => format!("{}?TOKEN={}", base, t),
        None => base,
    }
}

/// Fetch a standalone WebVTT version of a text track from an asset.
///
/// URL pattern: `https://stream.mux.com/{PLAYBACK_ID}/text/{TRACK_ID}.vtt`
pub fn text_track_url(playback_id: &str, track_id: &str, token: Option<&str>) -> String {
    let base = format!("{}/{}/text/{}.vtt", BASE, playback_id, track_id);
    match token {
        Some(t) => format!("{}?TOKEN={}", base, t),
        None => base,
    }
}

/// Fetch a standalone WebVTT version of a text track from an asset.
pub fn text_track_vtt_url(playback_id: &str, track_id: &str, token: Option<&str>) -> String {
    text_track_url(playback_id, track_id, token)
}

/// Fetch a [transcript of an asset](https://docs.mux.com/guides/add-autogenerated-captions-and-use-transcripts#retrieve-a-transcript).
/// This is only possible for assets with a text track generated using the
/// [VOD generated captions feature](https://docs.mux.com/guides/add-autogenerated-captions-and-use-transcripts).
///
/// URL pattern: `https://stream.mux.com/{PLAYBACK_ID}/text/{TRACK_ID}.txt`
pub fn transcript_url(playback_id: &str, track_id: &str, token: Option<&str>) -> String {
    let base = format!("{}/{}/text/{}.txt", BASE, playback_id, track_id);
    match token {
        Some(t) => format!("{}?TOKEN={}", base, t),
        None => base,
    }
}

fn append_query(base: String, qs: Vec<String>) -> String {
    if qs.is_empty() {
        base
    } else {
        format!("{}?{}", base, qs.join("&"))
    }
}
