/// Parameters for building an HLS manifest URL.
#[derive(Default)]
pub struct HlsParams {
    /// Set the relative end time of the asset (in seconds) when using the
    /// [instant clipping feature](https://docs.mux.com/guides/create-instant-clips).
    pub asset_end_time: Option<f64>,

    /// Set the relative start time of the asset (in seconds) when using the
    /// [instant clipping feature](https://docs.mux.com/guides/create-instant-clips).
    pub asset_start_time: Option<f64>,

    /// Set the default subtitles/captions language (BCP47 compliant language code).
    pub default_subtitles_lang: Option<String>,

    /// If set to true, EXT-X-PROGRAM-DATE-TIME tags will be omitted from HLS
    /// manifests for assets from live streams.
    pub exclude_pdt: Option<bool>,

    /// Set the maximum resolution of renditions included in the manifest.
    /// Accepted values: `"270p"`, `"360p"`, `"480p"`, `"540p"`, `"720p"`,
    /// `"1080p"`, `"1440p"`, `"2160p"`.
    pub max_resolution: Option<String>,

    /// Set the minimum resolution of renditions included in the manifest.
    /// Accepted values: `"270p"`, `"360p"`, `"480p"`, `"540p"`, `"720p"`,
    /// `"1080p"`, `"1440p"`, `"2160p"`.
    pub min_resolution: Option<String>,

    /// Set the end time of the asset created from a live stream when using the
    /// [instant clipping feature](https://docs.mux.com/guides/create-instant-clips).
    /// Provided as an epoch integer, compared to the program date time (PDT)
    /// generated by a live stream.
    pub program_end_time: Option<u64>,

    /// Set the start time of the asset created from a live stream when using the
    /// [instant clipping feature](https://docs.mux.com/guides/create-instant-clips).
    /// Provided as an epoch integer, compared to the program date time (PDT)
    /// generated by a live stream.
    pub program_start_time: Option<u64>,

    /// Include [HLS redundant streams](https://docs.mux.com/guides/play-your-videos#add-delivery-redundancy-with-redundant-streams)
    /// in the manifest.
    pub redundant_streams: Option<bool>,

    /// Set the logic to order renditions in the HLS manifest.
    /// Accepted values: `"desc"`.
    pub rendition_order: Option<String>,

    /// Add support for [timeline hover previews on Roku devices](https://docs.mux.com/guides/create-timeline-hover-previews#roku-trick-play).
    pub roku_trick_play: Option<bool>,

    /// Signed token (JWT) for secure video playback.
    pub token: Option<String>,
}

/// Valid filenames for static renditions.
/// [MP4 Support](https://docs.mux.com/guides/enable-static-mp4-renditions) must
/// be enabled on the asset before using these URLs.
pub enum StaticRendition {
    Capped1080p,
    High,
    Medium,
    Low,
    AudioOnly,
}

impl StaticRendition {
    pub fn filename(&self) -> &'static str {
        match self {
            StaticRendition::Capped1080p => "capped-1080p.mp4",
            StaticRendition::High => "high.mp4",
            StaticRendition::Medium => "medium.mp4",
            StaticRendition::Low => "low.mp4",
            StaticRendition::AudioOnly => "audio.m4a",
        }
    }
}
