/// Parameters for retrieving a thumbnail image from a video.
#[derive(Default)]
pub struct ThumbnailParams {
    /// The time (in seconds) of the video timeline where the image should be
    /// pulled. Defaults to the middle of the original video.
    pub time: Option<f64>,

    /// The width of the thumbnail (in pixels). Defaults to the width of the
    /// original video.
    pub width: Option<u32>,

    /// The height of the thumbnail (in pixels). Defaults to the height of the
    /// original video.
    pub height: Option<u32>,

    /// Rotate the image clockwise by the given number of degrees.
    /// Accepted values: 90, 180, 270.
    pub rotate: Option<u16>,

    /// Flip the image left-right after performing all other transformations.
    pub flip_h: Option<bool>,

    /// Flip the image top-bottom after performing all other transformations.
    pub flip_v: Option<bool>,

    /// How to fit a thumbnail within the specified width + height.
    /// Accepted values: `"preserve"`, `"stretch"`, `"crop"`, `"smartcrop"`, `"pad"`.
    pub fit_mode: Option<String>,

    /// When set to `true`, pulls the latest thumbnail from the playback ID of
    /// an ongoing live stream. Can only be used with live streams.
    pub latest: Option<bool>,

    /// Set the time of the thumbnail for an asset created from a live stream
    /// when using the instant clipping feature. Provided as an epoch integer,
    /// compared to the program date time (PDT) generated by a live stream.
    pub program_time: Option<u64>,

    /// Image format. Determines the file extension used in the URL.
    /// Accepted values: `"jpg"`, `"png"`, `"webp"`. Defaults to `"jpg"`.
    pub format: Option<String>,

    /// Signed token (JWT) for secure video playback.
    pub token: Option<String>,
}

/// Parameters for retrieving an animated GIF or WebP from a video.
#[derive(Default)]
pub struct AnimatedParams {
    /// The time (in seconds) of the video timeline where the animated image
    /// should begin. Defaults to 0.
    pub start: Option<f64>,

    /// The time (in seconds) of the video timeline where the animated image
    /// ends. Defaults to 5 seconds after the start. Maximum total duration is
    /// limited to 10 seconds; minimum total duration is 250ms.
    pub end: Option<f64>,

    /// The width in pixels. Default is 320px, or if height is provided, width
    /// is determined by preserving aspect ratio. Max width is 640px.
    pub width: Option<u32>,

    /// The height in pixels. The default height is determined by preserving
    /// aspect ratio with the width provided. Maximum height is 640px.
    pub height: Option<u32>,

    /// The frame rate of the generated image. Defaults to 15 fps. Max 30 fps.
    pub fps: Option<u32>,

    /// Image format. Determines the file extension used in the URL.
    /// Accepted values: `"gif"`, `"webp"`. Defaults to `"gif"`.
    pub format: Option<String>,

    /// Signed token (JWT) for secure video playback.
    pub token: Option<String>,
}

pub type AnimatedImageParams = AnimatedParams;

/// Parameters for retrieving a storyboard image or its metadata.
#[derive(Default)]
pub struct StoryboardParams {
    /// Image format. Determines the file extension used in the URL.
    /// Accepted values: `"jpg"`, `"png"`, `"webp"`. Defaults to `"jpg"`.
    pub format: Option<String>,

    /// Set the relative end time of the asset (in seconds) when using the
    /// instant clipping feature.
    pub asset_end_time: Option<f64>,

    /// Set the relative start time of the asset (in seconds) when using the
    /// instant clipping feature.
    pub asset_start_time: Option<f64>,

    /// Set the end time of the asset created from a live stream when using the
    /// instant clipping feature. Provided as an epoch integer, compared to the
    /// program date time (PDT) generated by a live stream.
    pub program_end_time: Option<u64>,

    /// Set the start time of the asset created from a live stream when using
    /// the instant clipping feature. Provided as an epoch integer, compared to
    /// the program date time (PDT) generated by a live stream.
    pub program_start_time: Option<u64>,

    /// Signed token (JWT) for secure video playback.
    pub token: Option<String>,
}

pub enum StoryboardImageExtension {
    Jpg,
    Png,
    Webp,
}

impl StoryboardImageExtension {
    pub fn as_str(&self) -> &'static str {
        match self {
            StoryboardImageExtension::Jpg => "jpg",
            StoryboardImageExtension::Png => "png",
            StoryboardImageExtension::Webp => "webp",
        }
    }
}
